### ISSUE TITLE
Password boxes and other dialogs have a hard time redrawing when the app is reselected

### ISSUE THREAD

**Issue by TAGray** [OptimalBI/optimal-spyglass-open-source#2]
The app contains code to redraw the dialog boxes when the app is re-selected so that the dialog box is not drawn over OS components.
This code is called by a focused window event listener which is not always fired

**Comment by dannyre** [comment]
From Trello: Investigate Drew's bug where copy/paste of credentials kept closing the prompt every time he switched. Drew ran it on: "Mac OSX 10.10.1, I've got a mix of JRE 1.6, 1.7 and 1.8 on here for various reasons too, but got it going with 1.8 :)"

**Comment by TAGray** [comment]
Improved system for now, will be looking at again
